parameters:  
  "service-dir":
    default: "sdk/servicenetworking"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/TrafficController.json"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-servicenetworking"
    package-name: "{package-dir}"