emit:
  - '@azure-tools/typespec-autorest'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    examples-directory: "{project-root}/examples"
  "@azure-tools/cadl-python":
    "basic-setup-py": true
    "package-version": 1.0.0b1
    "package-name": azure-mgmt-devopsinfrastructure
  "@azure-tools/cadl-csharp":
    save-inputs: false
    clear-output-folder: true
    namespace: Microsoft.DevOpsInfrastructure
    model-namespace: false