parameters:  
  "service-dir":
    default: "sdk/contosowidgetmanager"
  "dependencies":
    "additionalDirectories":
      - "specification/contosowidgetmanager/Contoso.WidgetManager.Shared/"
    default: ""
emit:
  - "@azure-tools/typespec-ts"
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/widgets.json"
  "@azure-tools/typespec-python":
    package-dir: "azure-contoso-widgetmanager"
    package-mode: "dataplane"
    package-name: "{package-dir}"
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Template.Contoso"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
  "@azure-tools/typespec-ts":
    title: "Contoso Widget Manager"
    generateMetadata: true
    generateTest: false
    "emitter-output-dir": "C:/repos/azure-sdk-for-js/sdk/contoso/contoso-widgetmanager-rest"
    packageDetails:
      name: "@azure-rest/contoso-widgetmanager-rest"
      description: "Contoso Widget Manager"
      version: "1.0.0-beta.1"
  "@azure-tools/typespec-java":
    package-dir: "azure-contoso-widgetmanager"
    namespace: com.azure.contoso.widgetmanager
