emit: [
  # "@azure-tools/typespec-apiview",
  # "@azure-tools/typespec-autorest",
  # "@azure-tools/typespec-csharp"
  "@azure-tools/typespec-ts",
]
# linter:
#   extends:
#     - "@azure-tools/typespec-azure-core/all"
options:
  "@azure-tools/typespec-csharp":
    namespace : "Azure.Developer.DevCenter"
    clear-output-folder : true
    # new-project : false
    # model-namespace : false
